#!/bin/bash
#
# Script to build transpiler Docker image.
#
# Needs root privileges or 'docker' group membership

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
. "${SCRIPT_DIR}/../inc.constants"
. "${SCRIPT_DIR}/../inc.functions"


# Defaults
DEFAULT_CLANG_VERSION=$(grep -E "FROM.*clang:" "${SCRIPT_DIR}/../../Dockerfile" | cut -d":" -f2)


# Functions
function usage {
    echo -e "Usage: ${0} [OPTIONS]"
    echo -e "  --docker-push\t(optional)"
    exit 1
}


# Command-line arguments
while [[ $# -gt 0 ]] ; do
    key="$1"
    case $key in
    --docker-push)
        docker_push=true
        ;;
    -h|--help)
        usage
        shift # past argument
        ;;
    *) # unknown option
        ;;
    esac
    shift # past argument or value
done


# Let's roll
image_tag=${DEFAULT_CLANG_VERSION}

echo "Building image tag ${image_tag}..."
safe docker build \
    --tag ${DOCKER_IMAGE}:${image_tag} .
if [ ${docker_push} ] ; then
    safe docker push ${DOCKER_IMAGE}:${image_tag}
fi

# Update 'latest' tag if script argument match defaults
if [ ${swiftlint} = ${DEFAULT_SWIFTLINT} ]; then
    echo "Tagging as 'latest'..."
    safe docker tag ${DOCKER_IMAGE}:${image_tag} ${DOCKER_IMAGE}:latest
    if [ ${docker_push} ] ; then
        safe docker push ${DOCKER_IMAGE}:latest
    fi
fi
